#include <math.h>
#include <time.h>
#include <stdlib.h>
#include <stdio.h>
#include <ctype.h>
#include <string.h>
#include <stdarg.h>
#include <limits.h>
#include <inttypes.h>
#include <assert.h>

//random number generator 

double randum (int64_t  *seed)
{
  int64_t  sum, mult0, mult1, seed0, seed1, seed2, newseed0, newseed1, newseed2;
  double res;

  mult0 = 1549;
  seed0 = *seed & 4095;
  sum  = mult0 * seed0;
  newseed0 = sum & 4095;
  sum >>= 12;
  seed1 = (*seed >> 12) & 4095;
  mult1 =  406;
  sum += mult0 * seed1 + mult1 * seed0;
  newseed1 = sum & 4095;
  sum >>= 12;
  seed2 = (*seed >> 24) & 255;
  sum += mult0 * seed2 + mult1 * seed1;
  newseed2 = sum & 255;

  *seed = newseed2 << 24 | newseed1 << 12 | newseed0;
  res = 0.00390625 * (newseed2 + 0.000244140625 * (newseed1 + 0.000244140625 * newseed0));

  return res;
}

//function to generate permutation of array with n integers 

void makePermutation(int *perm, int lower, int n, int64_t *seed)
{    
  int  i, j, k;

  for (i = lower; i <= n; i++)    
    perm[i] = i;               

  for (i = lower; i <= n; i++) 
    {    
      k =  (int)((double)(n + 1 - i) * randum(seed));

      assert(i + k <= n);
      
      j        = perm[i];
      perm[i]     = perm[i + k];
      perm[i + k] = j; 
    }
}


int main (int argc, char *argv[])
{
  int 
    i,
    j,   
    length,
    *p,
    //number of random permutations of sum calculation
    randomizations = 1000;
  
  //random number seed
  int64_t 
    seed = 12345;
  
  //read in binary file containing alignment length and per-site log likelihoods
  FILE 
    *f = fopen("binary.in", "rb");

  //array to store per-site log likes
  double 
    *a;

  //read alignment length
  fread(&length, sizeof(int), 1, f);


  //allocate array
  a = (double *)malloc(sizeof(double) * length);
 
  //read-in per-site log likes 
  fread(a, sizeof(double), length, f);

  {
    //starting minimum and maximum values
    double      
      min = 10.0,
      max = -1.0E300;
    
    //allocate integer array for permuting site positions
    p = (int *)malloc(sizeof(int) * (length + 1));
    
    //print number of sites
    printf("\nNumber of sites :%d \n", length);

    printf("\nGenerating %d permutations of the per-site log likelihood addition order\n\n", randomizations);
          
    //loop over permutations 
    for(i = 0; i < randomizations; i++)
      {
	//accumulateed log likelihoods 
	double 
	  sum = 0.0;
	
	//generate a permutation
	makePermutation(p, 1, length, &seed);
	
	//loop over sites 
	for(j = 1; j <= length; j++)
	  {
	    int 
	      index = p[j] - 1;
	    
	    assert(index >= 0 && index < length);
	    
	    //and calculate the sum over all per-site likelihoods 
	    sum += a[index];
	  }
	
	//set minimum and maximum log likelihood generated by permuting the addition order
	if(sum < min)
	  min = sum;
	if(sum > max)
	  max = sum;
	
      }
    
    //print out result
    printf("\nmaximum log likelihood: \t %8.8f\nminimum log likelihood: \t %8.8f\nlog likelihood difference: %8.20f\n\n", max, min, fabs(max - min));
    
    free(p);
  }

  free(a);
  fclose(f);
}
